### ISSUE TITLE
Prototyp strony

### ISSUE THREAD

**Issue by Aviuz** [MolibdenowyMikolaj/TiM#5]
-strona ma być napisana w oparciu o Angulara (najlepiej Angular 2)
-dane z servera symulowane, zaznaczony fragment gdzie będą popierane, za pomocą PROMISE*
-aplikacja na zasadzie zakładek. Aplikacja powinna posiadać widok generalny - master, oraz część główną jako poszczególne widoki zakładek

*Poradnik do promise http://andyshora.com/promises-angularjs-explained-as-cartoon.html

**Comment by MolibdenowyMikolaj** [comment]
Bez promise prototyp natenczas, proszę o informacje o poszerzeniu funkcjonalności i konfrontację wizji wykonania.

[Angular.zip](https://github.com/MolibdenowyMikolaj/TiM/files/1034351/Angular.zip)
